version: '3.4'

services:

  nosqldata:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  webshoppingapigw:
    image: envoyproxy/envoy-alpine

  basketdata:
    image: redis:alpine

