version: '3.4'

services:

  rabbitmq:
    ports:
    - "25672:15672"
    - "6672:5672"

  webshoppingapigw:
    volumes:
    - ./ApiGateways/Envoy/config/webshopping:/etc/envoy
    ports:
    - "6202:80"
    - "25202:8001"
    - "7202:10000"
  basketdata:
    ports:
      - "7379:6379"
    volumes:
      - eshop-basketdata:/data

volumes:
  eshop-basketdata:
    external: false