version: '3.4'

services:

  rabbitmq:
    ports:
    - "15672:15672"
    - "5672:5672"

  webshoppingapigw:
    volumes:
    - ./ApiGateways/Envoy/config/webshopping:/etc/envoy
    ports:
    - "5202:80"
    - "15202:8001"